version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ledger_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ledger_db
      TZ: Asia/Taipei
    # ports:
    #   - "5418:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: ledger_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ledger_db
    # ports:
    #   - "8018:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: ledger_frontend
    restart: always
    ports:
      - "3018:80"
    depends_on:
      - backend
