"""payment_status_to_numeric

Revision ID: 84fcd851ea78
Revises: c66285d709bb
Create Date: 2026-04-05 22:45:55.634020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fcd851ea78'
down_revision: Union[str, Sequence[str], None] = 'c66285d709bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('ledgers', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               postgresql_using="CASE WHEN payment_status ~ '^[0-9]+(\\.[0-9]+)?$' THEN payment_status::numeric(15,2) ELSE NULL END")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledgers', 'payment_status',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
